# Generated by Django 5.0 on 2024-01-09 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_manage", "0009_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="quantity",
        ),
    ]
