# Generated by Django 5.0 on 2024-01-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cop_name', models.CharField(max_length=50)),
                ('cop_price', models.BigIntegerField()),
                ('code', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to', models.DateField()),
            ],
        ),
    ]
