# Generated by Django 4.2.7 on 2024-01-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupenapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupons",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
