# Generated by Django 4.2.7 on 2024-01-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manage', '0010_remove_products_quantity'),
        ('logintohome', '0005_customuser1_referral_link'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manage.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logintohome.customuser1')),
            ],
        ),
    ]
