# Generated by Django 4.2.7 on 2024-01-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("logintohome", "0005_customuser1_referral_link"),
        ("todelivery", "0031_alter_order_details_addres"),
        ("userprofile", "0002_product_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="return_requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("return_status", models.CharField(max_length=50)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todelivery.ordered_items",
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todelivery.order_details",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logintohome.customuser1",
                    ),
                ),
            ],
        ),
    ]
