# Generated by Django 4.2.7 on 2024-01-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0005_remove_return_requests_return_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="return_requests",
            name="return_date",
            field=models.DateField(null=True),
        ),
    ]
