# Generated by Django 4.2.7 on 2024-01-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product_manage", "0010_remove_products_quantity"),
        ("category_management", "0002_category_is_listed"),
    ]

    operations = [
        migrations.CreateModel(
            name="product_offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.IntegerField()),
                (
                    "pro_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_manage.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="category_offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.IntegerField()),
                (
                    "cat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category_management.category",
                    ),
                ),
            ],
        ),
    ]
