"""
Django settings for furni project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path, os
# from decoj

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-otcykcc@d7(a&_eeb6r%4sfcv4khqqlkfc%dh^!t3!z6)@qm&%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['34.227.92.4','0.0.0.0',"*"]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO','https')


CSRF_TRUSTED_ORIGINS=['http://3.237.182.41',
'https://13.60.16.182',
'http://0.0.0.0',
'https://0.0.0.0',
'http://0.0.0.0:9090']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "logintohome",
    "customadmin",
    "category_management",
    "product_manage",
    "afterlogin",
    "todelivery",
    "userprofile",
    "coupenapp",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ALLOWED_HOSTS = ['localhost',
                  '127.0.0.1']

ROOT_URLCONF = "furni.urls"
# CORS_ALLOWED_ORIGINS = [
# "http://13.60.16.182",
# "https://13.60.16.182",
# "http://0.0.0.0",
# "https://0.0.0.0",
# "http://0.0.0.0:9090"]

# CORS_ALLOW_HEADERS = [
#                  'access-control-allow-headers',
#                    'access-control-allow-methods',
#                   'access-control-allow-origin',
#                     'content-type',
#                      'x-csrftoken']

# CORS_ALLOW_METHODS = [
#                'DELETE',
#                'GET',
#                'OPTIONS',
#                'PATCH',
#                'POST',
#                'PUT']

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "logintohome/templates",
            BASE_DIR / "customadmin/templates1",
            BASE_DIR / "afterlogin/templates1",
            BASE_DIR / "product_manage/templates",
            BASE_DIR / "category_management/templates",
            BASE_DIR / "todelivery/templates",
            BASE_DIR / "userprofile/templates",
            BASE_DIR / "coupenapp/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "furni.wsgi.application"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = "muhammedmamu2906@gmail.com"
EMAIL_HOST_PASSWORD = "grab xgdk npul bals"
EMAIL_USE_TLS = True  # Set it to False if your email server doesn't support TLS


WSGI_APPLICATION = "furni.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

STATIC_ROOT = os.path.join(BASE_DIR,'asset')

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
         "NAME": "furnidatabase",
         "USER": "muhammed",
        "PASSWORD": "Rabimammi2906$$$",
        "HOST": "localhost",  # or your database host
        "PORT": "5432",  # By default, PostgreSQL uses port 5432
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# STATICFILES_DIRS = [
#     os.path.join(
#         BASE_DIR / "static",
#     )
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(
    BASE_DIR / "media",
)


RAZORPAY_TEST_KEY_ID = "rzp_test_waokdwpF3Rteg3"
RAZORPAY_KEY_SECRET = "arKa0TSPBX7KMr6q8t1CqQ9k"
