# Generated by Django 5.0 on 2023-12-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logintohome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser1',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
