# Generated by Django 4.2.7 on 2024-01-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logintohome", "0004_customuser1_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser1",
            name="referral_link",
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
