# Generated by Django 5.0 on 2023-12-25 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logintohome', '0003_customuser1_otp_fld_customuser1_otp_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('pin', models.BigIntegerField(max_length=6)),
                ('emial', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logintohome.customuser1')),
            ],
        ),
    ]
