# Generated by Django 5.0 on 2023-12-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todelivery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="pin",
            field=models.BigIntegerField(),
        ),
    ]
