# Generated by Django 5.0 on 2023-12-27 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logintohome', '0004_customuser1_profile'),
        ('todelivery', '0008_ordered_items_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_items',
            name='addres',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordered_items',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logintohome.customuser1'),
            preserve_default=False,
        ),
    ]
