# Generated by Django 5.0 on 2023-12-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todelivery', '0010_alter_ordered_items_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordered_items',
            old_name='user_id',
            new_name='user',
        ),
    ]
