# Generated by Django 5.0 on 2023-12-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todelivery", "0016_alter_ordered_items_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordered_items",
            name="expected",
            field=models.DateField(null=True),
        ),
    ]
