# Generated by Django 5.0 on 2024-01-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todelivery', '0017_ordered_items_expected'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
