# Generated by Django 5.0 on 2023-12-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afterlogin", "0001_initial"),
        ("logintohome", "0003_customuser1_otp_fld_customuser1_otp_secret_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="logintohome.customuser1",
            ),
        ),
    ]
