# Generated by Django 5.0 on 2023-12-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afterlogin", "0002_alter_cart_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
