# Generated by Django 5.0 on 2024-01-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterlogin', '0008_remove_wishlist_stock'),
        ('product_manage', '0010_remove_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_manage.variant'),
        ),
    ]
