# Generated by Django 4.2.7 on 2024-01-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afterlogin", "0010_wishlist_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
